applications:
  frontend:
    name: globalbank-frontend
    namespace: dev
    repoPath: globalbank-frontend

  backend:
    name: globalbank-backend
    namespace: dev
    repoPath: globalbank-backend

  cluster:
    server: https://192.168.100.67:32771